### ISSUE TITLE
Leetcode Rating

### ISSUE THREAD

**Issue by Siddhant-K-code** [kehsihba19/CP-Badges#8]
Can we Fetch Leetcode Ratings also? I tried using Beautiful Soup, unable to implement it.

Any Idea, how can we Fetch user ratings from Leetcode ?

**Comment by kehsihba19** [comment]
It's actually not available for all profiles. 
But even then, we can scrape this component (class="css-57pydk") for finding the rating points of a user.
Not everyone who is in CP uses leetcode, this why I didn't add this feature yet.
But I will be happy to add if someone makes a pull request of this feature.
Cheers! :)

**Comment by Siddhant-K-code** [comment]
> But even then, we can scrape this component (class="css-57pydk")

I tried it yesterday, unable to get it

**Comment by shubhamdhingra38** [comment]
@kehsihba19 I can work on this. I'll hack around something, although I think this can be done using API. They use GraphQL and their API didn't seem to be that restrictive (rate-limit wise) when I last played around with it.

**Comment by kehsihba19** [comment]
@shubhamdhingra38 
Go ahead. Will be happy to merge the PR.
:)
