### ISSUE TITLE
Rating Colors on Codeforces are Wrongly Assigned

### ISSUE THREAD

**Issue by fairy-lettuce** [kehsihba19/CP-Badges#9]
According to [this](https://en.wikipedia.org/wiki/Codeforces) (this rating table should be up to date), the rating boundary between Candidate Master and Master (should be 2099 but 2199 on data.py) seems wrong. My rating is 2132 now but the badge shows purple.
[![Badge](https://cp-logo.vercel.app/codeforces/fairy_lettuce)](https://codeforces.com/profile/fairy_lettuce)

**Comment by kehsihba19** [comment]
Will be fixing the codeforces bug in the next release.
Thank you for pointing out the issues.
:)

**Comment by kehsihba19** [comment]
@fairy-lettuce 
Fixed :)
